// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wndnrubgscozclgjsmhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZG5ydWJnc2NvemNsZ2pzbWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODQwNTcsImV4cCI6MjA2Mzk2MDA1N30.yqD5C_NXLigHj1ElOabV0N0NRwBdITvlccl1-tAlrEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);