// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwnjdcqepkdmbecbpcod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bmpkY3FlcGtkbWJlY2JwY29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTU2MjUsImV4cCI6MjA2NjI5MTYyNX0.4cy0eYv6ydR47yrijHAduT5qLlPkK8i10CIp7lt8_zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);