
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aokwwwbyiutzfugncxdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFva3d3d2J5aXV0emZ1Z25jeGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQxNzksImV4cCI6MjA2NTM4MDE3OX0.24SMSOcLV5khm76GJlAlHT_EkammXefpFm4wSxG8n4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
